/**
 * Article images from real sources only: a Klipara clip's own cover, a
 * screenshot of the site's own pages, or a graphic rendered from a branded
 * HTML template (a cover, numbered steps, a bar chart of given numbers). No
 * image is generated by a model, so none can show a person, a screen or a
 * product that does not exist. Rendered images are written under the
 * plugin's media directory and served publicly so the site's publisher can
 * copy them into its own media library; the article then links the site's
 * copy.
 */

import { randomBytes } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { CaptureDriver, ScreenedUrl } from '@deepseek-ai/dsh-host-capture'
import type { Site } from './types.ts'

/** One image request, as the writer asks for it. */
export type ImageRequest =
  | { kind: 'clip-cover'; sampleId: string }
  | { kind: 'screenshot'; url: string; selector?: string; mobile: boolean }
  | { kind: 'graphic'; template: 'cover'; title: string; subtitle: string }
  | { kind: 'graphic'; template: 'steps'; title: string; steps: string[] }
  | { kind: 'graphic'; template: 'chart'; title: string; bars: { label: string; value: number }[]; unit: string; source: string }

/** A made image: where the publisher can fetch it. */
export interface MadeImage {
  /** Public URL the site's publisher copies from. */
  sourceUrl: string
  width: number
  height: number
  /** What it is, for the tool's reply. */
  description: string
}

/** Colours, fonts and name a graphic is drawn in. Colours are CSS colour values (hex, rgb() or oklch()). */
export interface Brand {
  name: string
  accent: string
  paper: string
  ink: string
  /** Google Fonts family for headings, or empty for the system sans. */
  displayFont: string
  /** Google Fonts family for body text, or empty for the system sans. */
  bodyFont: string
}

/** What the image maker needs. */
export interface ImageDeps {
  driver: CaptureDriver
  /** Screens a URL before the browser opens it (public addresses only). */
  screen: (url: string) => Promise<ScreenedUrl>
  fetch: typeof fetch
  /** Directory rendered PNGs are written to. */
  mediaDir: string
  /** Public URL of a rendered file, by its file name. */
  publicUrl: (file: string) => string
}

const SAMPLE_ID = /^[A-Za-z0-9_-]{6,40}$/u

function escape(value: string): string {
  return value.replace(/[&<>"']/gu, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', '\'': '&#39;' })[c] ?? c)
}

const COLOR = /^(?:#[0-9a-fA-F]{3,8}|(?:rgb|rgba|hsl|hsla|oklch|oklab|lab|lch)\([0-9a-zA-Z.%\s,/+-]{1,60}\))$/u
const FONT = /^[A-Za-z0-9 ]{2,40}$/u

/** Lightness of a CSS colour, 0 to 1, for hex and oklch values; undefined for others. */
function lightness(color: string): number | undefined {
  const ok = /^oklch\(\s*([\d.]+)(%?)/iu.exec(color)
  if (ok?.[1] !== undefined) return ok[2] === '%' ? Number(ok[1]) / 100 : Number(ok[1])
  const hex = /^#([0-9a-fA-F]{6})$/u.exec(color)?.[1]
  if (hex === undefined) return undefined
  const [r, g, b] = [0, 2, 4].map(i => parseInt(hex.slice(i, i + 2), 16) / 255) as [number, number, number]
  return 0.2126 * r + 0.7152 * g + 0.0722 * b
}

/** Every literal value a stylesheet gives one of these custom properties, in source order. */
function customValues(css: string, names: readonly string[]): string[] {
  const out: string[] = []
  for (const name of names) {
    for (const m of css.matchAll(new RegExp(`--${name}\\s*:\\s*([^;}]+)`, 'giu'))) {
      const value = (m[1] ?? '').trim()
      if (value !== '' && !value.startsWith('var(')) out.push(value)
    }
  }
  return out
}

/**
 * Read a site's brand from its own pages: the theme colour, and the colour and
 * font custom properties its stylesheets declare (light-mode values chosen by
 * lightness). Anything it cannot find falls back to a plain dark-on-white look.
 * @param fetcher - HTTP.
 * @param baseUrl - the site's origin.
 * @param signal - cancels the reads.
 * @returns the brand as found; the site name is filled by the caller.
 */
export async function detectBrand(fetcher: typeof fetch, baseUrl: string, signal: AbortSignal): Promise<Omit<Brand, 'name'>> {
  const brand = { accent: '#1f2937', paper: '#ffffff', ink: '#111111', displayFont: '', bodyFont: '' }
  const get = async (url: string): Promise<string> => {
    const response = await fetcher(url, { signal: AbortSignal.any([signal, AbortSignal.timeout(15_000)]) })
    return response.ok ? (await response.text()).slice(0, 600_000) : ''
  }
  let css = ''
  try {
    const html = await get(baseUrl)
    const theme = /<meta[^>]+name=["']theme-color["'][^>]+content=["']([^"']+)["']/iu.exec(html)?.[1]
    if (theme !== undefined && COLOR.test(theme)) brand.accent = theme
    css = [...html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/giu)].map(m => m[1] ?? '').join('\n')
    const origin = new URL(baseUrl).origin
    const links = /<link[^>]+rel=["']stylesheet["'][^>]*href=["']([^"']+)["']|<link[^>]+href=["']([^"']+\.css[^"']*)["']/giu
    const sheets = [...html.matchAll(links)]
      .map(m => m[1] ?? m[2] ?? '').filter(Boolean).map(h => new URL(h, origin)).filter(u => u.origin === origin).slice(0, 4)
    for (const sheet of sheets) css += `\n${await get(sheet.href)}`
  } catch (error) {
    // An unreachable site leaves the plain look; the graphic still renders.
    if (signal.aborted) throw error
    return brand
  }
  // Names in priority order: a site's own design tokens beat a component library's generic ones.
  const firstNamed = (names: string[]): string[] => {
    for (const name of names) {
      const values = customValues(css, [name]).filter(v => COLOR.test(v))
      if (values.length > 0) return values
    }
    return []
  }
  const papers = firstNamed(['color-paper', 'paper', 'color-background', 'background', 'bg'])
  const inks = firstNamed(['color-ink', 'ink', 'color-text', 'color-foreground', 'foreground', 'text'])
  const accents = firstNamed(['color-accent', 'color-brand', 'brand', 'color-primary', 'accent', 'primary'])
  const lightest = (values: string[]): string | undefined => values.toSorted((a, b) => (lightness(b) ?? 0) - (lightness(a) ?? 0))[0]
  const darkest = (values: string[]): string | undefined => values.toSorted((a, b) => (lightness(a) ?? 1) - (lightness(b) ?? 1))[0]
  brand.paper = lightest(papers) ?? brand.paper
  brand.ink = darkest(inks) ?? brand.ink
  // The light-mode accent is the darker of a site's accent pair, but never a near-black neutral.
  const grey = /oklch\(\s*[\d.]+%?\s+0(?:\.0+)?\s/iu
  const accent = accents.filter(a => (lightness(a) ?? 0.5) > 0.25 && (lightness(a) ?? 0.5) < 0.75 && !grey.test(a))
  brand.accent = darkest(accent) ?? brand.accent
  const family = (names: string[]): string => {
    const first = customValues(css, names)[0]?.split(',')[0]?.trim().replace(/^["']|["']$/gu, '') ?? ''
    return FONT.test(first) ? first : ''
  }
  brand.displayFont = family(['font-display', 'font-heading', 'font-serif'])
  brand.bodyFont = family(['font-body', 'font-sans'])
  return brand
}

/**
 * The brand a site's graphics use: what the owner set on the site, filled in from what its pages declare.
 * @param fetcher - HTTP.
 * @param site - the site.
 * @param signal - cancels the reads.
 * @returns the brand.
 */
export async function siteBrand(fetcher: typeof fetch, site: Site, signal: AbortSignal): Promise<Brand> {
  const set = site.brand
  const complete = set !== undefined && set.accent !== '' && set.paper !== '' && set.ink !== ''
  const found = complete ? undefined : await detectBrand(fetcher, site.baseUrl, signal)
  const pick = (owner: string | undefined, fallback: string | undefined): string => owner !== undefined && owner !== '' ? owner : fallback ?? ''
  return {
    name: site.name,
    accent: pick(set?.accent, found?.accent),
    paper: pick(set?.paper, found?.paper),
    ink: pick(set?.ink, found?.ink),
    displayFont: pick(set?.displayFont, found?.displayFont),
    bodyFont: pick(set?.bodyFont, found?.bodyFont),
  }
}

/**
 * The HTML of a template graphic. Everything is inline, so the page renders with no network.
 * @param request - the graphic.
 * @param brand - colours and name.
 * @returns the document and the card size.
 */
export function templateHtml(request: Extract<ImageRequest, { kind: 'graphic' }>, brand: Brand): { html: string; width: number; height: number } {
  const color = (value: string, fallback: string): string => COLOR.test(value) ? value : fallback
  const accent = color(brand.accent, '#1f2937')
  const paper = color(brand.paper, '#ffffff')
  const ink = color(brand.ink, '#111111')
  const display = FONT.test(brand.displayFont) ? brand.displayFont : ''
  const body = FONT.test(brand.bodyFont) ? brand.bodyFont : ''
  const families = [display, body].filter(Boolean).map(f => `family=${encodeURIComponent(f).replace(/%20/gu, '+')}:wght@400;600;700;800`)
  const fonts = families.length === 0 ? '' : `<link rel="stylesheet" href="https://fonts.googleapis.com/css2?${families.join('&')}&display=block">`
  const sans = '"Liberation Sans","DejaVu Sans",Arial,sans-serif'
  const headFont = display === '' ? sans : `"${display}",Georgia,serif`
  const textFont = body === '' ? sans : `"${body}",${sans}`
  const width = 1200
  const shell = (height: number, content: string): string => `<!doctype html><html><head><meta charset="utf-8">${fonts}<style>
*{box-sizing:border-box;margin:0}body{background:${paper}}
#card{width:${String(width)}px;height:${String(height)}px;background:${paper};color:${ink};font-family:${textFont};
padding:68px 80px;display:flex;flex-direction:column;position:relative;overflow:hidden}
.rule{position:absolute;left:80px;right:80px;bottom:64px;height:4px;background:${accent}}
.brand{font-family:${headFont};font-size:30px;font-weight:700;color:${ink};letter-spacing:-.01em}
.brand::after{content:"";display:block;width:64px;height:4px;background:${accent};margin-top:6px}
h1{font-family:${headFont};font-size:${request.template === 'cover' ? '70' : '48'}px;line-height:1.06;font-weight:700;margin-top:${request.template === 'cover' ? '56' : '36'}px;
letter-spacing:-.02em;overflow-wrap:anywhere;max-width:1000px}
.sub{font-size:30px;line-height:1.4;margin-top:28px;opacity:.75;max-width:960px}
ol{list-style:none;margin-top:40px;display:flex;flex-direction:column;gap:24px}
li{display:flex;gap:24px;align-items:center;font-size:31px;line-height:1.3}
.n{flex:none;width:56px;height:56px;border-radius:28px;background:${accent};color:${paper};font-family:${headFont};font-weight:700;font-size:28px;
display:flex;align-items:center;justify-content:center}
.chart{margin-top:44px;display:flex;flex-direction:column;gap:20px}
.row{display:grid;grid-template-columns:300px 1fr 170px;gap:20px;align-items:center;font-size:27px}
.track{height:36px;background:color-mix(in srgb,${ink} 8%,transparent);border-radius:4px;overflow:hidden}.fill{height:100%;background:${accent}}
.val{font-weight:700;text-align:right}.src{position:absolute;left:80px;bottom:84px;font-size:19px;opacity:.65}
</style></head><body><div id="card"><div class="brand">${escape(brand.name)}</div>${content}<div class="rule"></div></div></body></html>`
  switch (request.template) {
    case 'cover':
      return { width, height: 630, html: shell(630, `<h1>${escape(request.title)}</h1>${request.subtitle === '' ? '' : `<p class="sub">${escape(request.subtitle)}</p>`}`) }
    case 'steps': {
      const height = Math.max(630, 330 + request.steps.length * 82)
      const items = request.steps.map((step, i) => `<li><span class="n">${String(i + 1)}</span><span>${escape(step)}</span></li>`).join('')
      return { width, height, html: shell(height, `<h1>${escape(request.title)}</h1><ol>${items}</ol>`) }
    }
    case 'chart': {
      const height = Math.max(675, 400 + request.bars.length * 58)
      const max = Math.max(...request.bars.map(b => b.value), 1)
      const rows = request.bars.map(b => `<div class="row"><span>${escape(b.label)}</span><div class="track"><div class="fill" style="width:${String(Math.max(1, Math.round((b.value / max) * 100)))}%"></div></div><span class="val">${escape(`${b.value.toLocaleString('en')}${request.unit}`)}</span></div>`).join('')
      return { width, height, html: shell(height, `<h1>${escape(request.title)}</h1><div class="chart">${rows}</div><p class="src">Source: ${escape(request.source)}</p>`) }
    }
  }
}

/**
 * Check a request before anything is fetched or rendered.
 * @param site - the site the image is for.
 * @param request - the request.
 * @returns the reason it is refused, or undefined.
 */
export function imageProblem(site: Site, request: ImageRequest): string | undefined {
  switch (request.kind) {
    case 'clip-cover':
      if (site.kind !== 'klipara') return 'Clip covers come from Klipara samples; this site does not publish through Klipara.'
      return SAMPLE_ID.test(request.sampleId) ? undefined : 'sample_id must be the id from a /s/<id> link.'
    case 'screenshot': {
      let url: URL
      try {
        url = new URL(request.url)
      } catch {
        return 'url is not a URL.'
      }
      // Other people's pages are theirs: only the site's own pages are photographed.
      if (url.origin !== new URL(site.baseUrl).origin) return `Screenshots are of ${site.name}'s own pages only (${new URL(site.baseUrl).origin}).`
      return undefined
    }
    case 'graphic':
      if (request.title.trim() === '') return 'A graphic needs a title.'
      if (request.template === 'steps' && (request.steps.length < 2 || request.steps.length > 8)) return 'A steps graphic needs 2 to 8 steps.'
      if (request.template === 'chart') {
        if (request.bars.length < 2 || request.bars.length > 10) return 'A chart needs 2 to 10 bars.'
        if (request.bars.some(b => !Number.isFinite(b.value) || b.value < 0)) return 'Chart values must be zero or more.'
        if (request.source.trim() === '') return 'A chart needs the source of its numbers (real data only: Search Console, the owner\'s figures, a cited study).'
      }
      return undefined
  }
}

/**
 * Make one image.
 * @param deps - browser, URL screen, HTTP and media directory.
 * @param site - the site.
 * @param request - the image, already checked with {@link imageProblem}.
 * @param brand - colours for a graphic.
 * @param signal - cancels the work.
 * @returns where the publisher can fetch it.
 */
export async function makeImage(deps: ImageDeps, site: Site, request: ImageRequest, brand: Brand, signal: AbortSignal): Promise<MadeImage> {
  if (request.kind === 'clip-cover') {
    const sourceUrl = `${new URL(site.baseUrl).origin}/s/${encodeURIComponent(request.sampleId)}/poster.jpg`
    const head = await deps.fetch(sourceUrl, { method: 'HEAD', signal: AbortSignal.any([signal, AbortSignal.timeout(15_000)]) })
    if (!head.ok) throw new Error(`Klipara has no cover for sample ${request.sampleId} (HTTP ${String(head.status)}).`)
    return { sourceUrl, width: 0, height: 0, description: `the cover of Klipara sample ${request.sampleId}` }
  }
  let png: Uint8Array
  let width: number
  let height: number
  let description: string
  if (request.kind === 'screenshot') {
    const screened = await deps.screen(request.url)
    width = request.mobile ? 390 : 1280
    height = request.mobile ? 844 : 800
    const shot = await deps.driver.capture({
      url: screened.url.href, addresses: screened.addresses, literalHost: screened.literal, width, height, fullPage: false,
      deviceScaleFactor: request.mobile ? 2 : 1, mobile: request.mobile, waitMs: 1500, darkMode: false,
      ...request.selector === undefined || request.selector === '' ? {} : { selector: request.selector },
    }, signal)
    png = shot.png
    description = `a screenshot of ${request.url}${request.selector === undefined ? '' : ` (${request.selector})`}`
  } else {
    const page = templateHtml(request, brand)
    width = page.width
    height = page.height
    const shot = await deps.driver.capture({
      url: `data:text/html;base64,${Buffer.from(page.html).toString('base64')}`, addresses: [], literalHost: true,
      width: page.width, height: page.height, fullPage: false, deviceScaleFactor: 1, mobile: false, waitMs: 1500, darkMode: false, selector: '#card',
    }, signal)
    png = shot.png
    description = `a ${request.template} graphic in ${brand.name}'s colours`
  }
  await mkdir(deps.mediaDir, { recursive: true })
  const file = `${randomBytes(12).toString('hex')}.png`
  await writeFile(join(deps.mediaDir, file), png)
  return { sourceUrl: deps.publicUrl(file), width, height, description }
}
